# Generated by Django 6.0.6 on 2026-08-22 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGIN_LOCKED', 'Account Locked'), ('LOGOUT', 'Logout'), ('REGISTER_FARMER', 'Registered Farmer'), ('REGISTER_KAGAWAD', 'Registered Kagawad'), ('SCAN_UPLOAD', 'AI Scan Uploaded'), ('ALERT_READ', 'Alert Marked Read')], max_length=30)),
                ('details', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, help_text='The user who performed or triggered the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
