# Generated by Django 6.0.6 on 2026-09-06 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction_deg', models.IntegerField()),
                ('wind_cardinal', models.CharField(default='N', max_length=10)),
                ('precipitation', models.FloatField(default=0.0)),
                ('condition', models.CharField(default='Unknown', max_length=30)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather_state', to='farms.farm')),
            ],
        ),
    ]
