# Generated by Django 6.0.6 on 2026-07-04 15:02

# pyrefly: ignore [missing-import]
import django.db.models.deletion
# pyrefly: ignore [missing-import]
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CRITICAL', 'Critical Outbreak'), ('AT_RISK', 'At Risk Zone'), ('MONITORING', 'Monitoring'), ('RESOLVED', 'Resolved / Inactive')], default='CRITICAL', max_length=20)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction_deg', models.IntegerField()),
                ('wind_cardinal', models.CharField(default='N', max_length=10)),
                ('spread_velocity', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot', to='diagnostics.leafscan')),
            ],
        ),
    ]
