# Generated by Django 6.0.6 on 2026-07-04 15:02

# pyrefly: ignore [missing-import]
import django.db.models.deletion    
# pyrefly: ignore [missing-import]
from django.conf import settings
# pyrefly: ignore [missing-import]
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeafScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='leaf_scans/')),
                ('detected_disease', models.CharField(choices=[('HEALTHY', 'Healthy'), ('BLB', 'Bacterial Leaf Blight'), ('BLAST', 'Rice Blast'), ('BROWN_SPOT', 'Brown Spot')], default='HEALTHY', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_scans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
