# Generated by Django 6.1 on 2026-09-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leafscan',
            name='affected_area_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leafscan',
            name='heatmap',
            field=models.ImageField(blank=True, null=True, upload_to='leaf_scans/heatmaps/'),
        ),
        migrations.AddField(
            model_name='leafscan',
            name='lesion_boxes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leafscan',
            name='segmentation_mask',
            field=models.ImageField(blank=True, null=True, upload_to='leaf_scans/masks/'),
        ),
    ]
