# Generated by Django 6.0.6 on 2026-09-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alter_alert_severity'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalityWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.CharField(max_length=50, unique=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('wind_direction_deg', models.IntegerField()),
                ('wind_cardinal', models.CharField(default='N', max_length=10)),
                ('precipitation', models.FloatField(default=0.0)),
                ('condition', models.CharField(default='Unknown', max_length=30)),
                ('checked_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
